# Version 0.1

# basic
FROM ubuntu:latest

# owner
MAINTAINER Stanley.Lei.Sun@gmail.com

# Operation
RUN apt-get -yqq update && apt-get install -yqq python3 \
    python-pip \
    python3-pip \
    unixodbc-dev \
    python-tk \
    uwsgi \
    uwsgi-plugin-python 

RUN mkdir -p /var/log/supervisor

WORKDIR /home
RUN git clone https://github.com/StanleyLeiSun/PlayGround.git && git checkout PythonLearning

WORKDIR /home/PlayGround/RobertLog/AzureWeb
RUN pip install -r requirements.txt

#VOLUME ["/var/log/apche2"]

#ADD html.tar /var/www
#COPY supervisord.conf /etc/supervisor/conf.d/supervisord.conf

#WORKDIR /var/www/html

ENV HOSTNAME shiyanloutest
ENV APACHE_RUN_USER www-data
ENV APACHE_RUN_GROUP www-data
ENV APACHE_LOG_DIR /var/log/apche2
ENV APACHE_PID_FILE /var/run/apache2.pid
ENV APACHE_RUN_DIR /var/run/apache2
ENV APACHE_LOCK_DIR /var/lock/apche2

EXPOSE 80

# 容器启动命令
CMD ["/usr/bin/supervisord"]